### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by noaho** [winstxnhdw/nllb-api#113]
Hi, 

I don't know what your intentions are with the new change introducing rate limits at [cb0e401c17a372a9422dbb56d5dcdb0d522a7f71](https://github.com/winstxnhdw/nllb-api/commit/cb0e401c17a372a9422dbb56d5dcdb0d522a7f71)

But it broke all of my translate workflows.. Now my scripts get rate limited and quit. 

Is it possible that this could be an environment variable or optional feature?

Cheers!

**Comment by winstxnhdw** [comment]
Hey, the rate-limiter is for the hosted API. If you are self-hosting the CPU build, you can just set the `EVENTS_PER_WINDOW` environment variable. The GPU build has no rate limiting by default.

FWIW, you might also want to look at batching your translations if you are already hitting the current rate limits.

**Comment by winstxnhdw** [comment]
Okay, but for the sake of backwards compatibility, I think it's best if I made this an optional feature instead.
