### ISSUE TITLE
start container offline

### ISSUE THREAD

**Issue by Q-si** [winstxnhdw/nllb-api#132]
Hello,
I can't start the docker container successfully when I try to use the system completely offline. I don't get any error, but the swagger page is not reachable. As soon as I do an activation on huggingface.co, it works. What is the reason for this and can I work around it?

**Comment by winstxnhdw** [comment]
Okay, I've pushed a fix for this in the latest commit.

**Comment by Q-si** [comment]
It works! You are my hero :)
