### ISSUE TITLE
I'm having a problem using CUDA

### ISSUE THREAD

**Issue by norick5243** [winstxnhdw/nllb-api#140]
I have the latest file
docker build -f Dockerfile.cuda-build -t nllb-api .
I ran it, but an error occurs during installation.
I was able to install it without any problems before, but now I can't use it.

 RuntimeError
58.68
58.68 Unable to find installation candidates for ctranslate2 (4.2.0)
58.68
58.68 at /opt/poetry/venv/lib/python3.12/site-packages/poetry/installation/chooser.py:74 in choose_for
58.72 70│
58.72 71│ links.append(link)
58.72 72│
58.73 73│ if not links:
58.73 → 74│ raise RuntimeError(f"Unable to find installation candidates for {package}")
58.73 75│
58.74 76│ # Get the best link
58.74 77│ chosen = max(links, key=lambda link: self._sort_key(package, link))
58.74 78│
58.75
58.75 Cannot install ctranslate2.

I felt like I could only access the API server once.
It feels like it is waiting for the next access until the translation process is finished.

I am testing using GTX1060, but it only works at about 30% of its performance.
Is there a better way to resolve the slow translation speed?

**Comment by winstxnhdw** [comment]
Fixed the issue with `ctranslate2` install. If you want to improve GPU efficiency, you should batch your translations. See the README.

**Comment by norick5243** [comment]
thank you. I was able to install it.

Does this mean that batch processing will be performed in parallel with this API server?

--gpus all
However, do you think that if you attach multiple GPUs to one computer, they will all work?

**Comment by winstxnhdw** [comment]
I am not sure, I haven't tested this before. You can give it a try.
