### ISSUE TITLE
how to use facebook/nllb-200-distilled-1.3B  model

### ISSUE THREAD

**Issue by DingQi1994** [winstxnhdw/nllb-api#143]
how to use facebook/nllb-200-distilled-1.3B  model，i want to change model for use it

**Comment by winstxnhdw** [comment]
It's already using the `facebook/nllb-200-distilled-1.3B` model. Only difference is that it has been converted for CTranslate2.

**Comment by DingQi1994** [comment]
来信已收到，请等待回复
