### ISSUE TITLE
change model

### ISSUE THREAD

**Issue by Q-si** [winstxnhdw/nllb-api#149]
Hi, 
I am not satisfied with the translation from English to German. For some reason, individual sentences get lost. Is it possible to use your API with a different model? 
Specifically, it would be the following model: https://huggingface.co/Helsinki-NLP/opus-mt-en-de

**Comment by winstxnhdw** [comment]
You'll have to check if it can be converted to a CTranslate2 model.

**Comment by Q-si** [comment]
Here is the same model converted to a CTranslate2 model --> https://huggingface.co/michaelfeil/ct2fast-opus-mt-en-de

**Comment by winstxnhdw** [comment]
You can try changing out the NLLB model for that model in here: https://github.com/winstxnhdw/nllb-api/blob/main/server/features/translator.py

You might have to change the tokenizer too.

**Comment by Q-si** [comment]
Okay, thank you! i will try it and give you a feedback.

**Comment by winstxnhdw** [comment]
You can try using `AutoTokenizer` instead. The link you sent earlier shows how.

**Comment by Q-si** [comment]
Now i get the follow error: 
This tokenizer cannot be instantiated. Please make sure you have 'sentencepiece' installed in order to use this tokenizer.

**Comment by winstxnhdw** [comment]
Well, yeah?

**Comment by Q-si** [comment]
I am a bit closer now :) I had to add some entries to pyproject.toml
Now i am able to start the docker. But when i try to execute a translation, i got an error. --> "Unprocessable Entity"
i think the problem is, that your api requires the 3 parameter **text**, **source** and **target**
the new model just requires the parameter **text**
What do you think? How can i desable the others?

**Comment by winstxnhdw** [comment]
Delete the two lines here: https://github.com/winstxnhdw/nllb-api/blob/main/server/schemas/v1/translation.py#L17

Only pass text here: https://github.com/winstxnhdw/nllb-api/blob/main/server/dependencies/translation.py#L27

Lastly, you'll have to change this method: https://github.com/winstxnhdw/nllb-api/blob/main/server/features/translator.py#L42

**Comment by Q-si** [comment]
i gave up. an other tokenizer error uccurs... :(

**Comment by winstxnhdw** [comment]
Not a problem.

**Comment by Q-si** [comment]
Hi, 
sorry for the renewed disruption.
i tried to use the following model --> OpenNMT/nllb-200-3.3B-ct2-int8
but i got the following error when i try to start the docker container:
"LocalEntryFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input"

I think there are some issues with downloading the model. Our host is in a network with strongly security settings. Is there a way to download the model manually and link this to the system?

**Comment by winstxnhdw** [comment]
Yes, but I don’t exactly know how. If you realised by now, a model from HuggingFace is always installed in your HuggingFace cache folder. On Linux, this is usually located at `$XDG_CACHE_HOME`. If you can manually install the model and put it there, the library will detect and use this model.
