### ISSUE TITLE
The readme.md may be  a bit confusing

### ISSUE THREAD

**Issue by sirfuwh** [winstxnhdw/nllb-api#152]
Nice work！ This is the best and fastest repo I've tried so far. I'm very grateful, even though it took me a while to figure it out, because the README.md file maybe a bit confusing. The section https://github.com/winstxnhdw/nllb-api#model-caching mentions the need to create a custom cache directory, which can be confusing, as the various Hugging Face download methods may result in different directory structures.
In reality,  don't need to create your own cache directory. You can simply point to the default Hugging Face cache directory (e.g., /root/.cache for the root user) instead.
btw： I want to use this model and API, and pair it with a browser extension. Where can I find a plugin like that to modify and adapt to this repo's API? thx！

**Comment by winstxnhdw** [comment]
Hey, thanks for the compliment!

> In reality, don't need to create your own cache directory. You can simply point to the default Hugging Face cache directory (e.g., /root/.cache for the root user) instead.

Unfortunately, the default cache directory is different from machine-to-machine and operating system to operating system, so this is the best compromise for now.

>  I want to use this model and API, and pair it with a browser extension. Where can I find a plugin like that to modify and adapt to this repo's API? 

Hmm.. I am not sure of any browser extensions that do this currently.

**Comment by sirfuwh** [comment]
ok, thanks!
