### ISSUE TITLE
Language Detection

### ISSUE THREAD

**Issue by Q-si** [winstxnhdw/nllb-api#161]
Is it possible to make a request to determine the language of my sended text?

**Comment by winstxnhdw** [comment]
No.

**Comment by Q-si** [comment]
:( that would be a great feature ;-)

**Comment by winstxnhdw** [comment]
NLLB doesn’t provide such a feature.

**Comment by Q-si** [comment]
ok

**Comment by winstxnhdw** [comment]
Welp, I've added a route to detect the source language.
