### ISSUE TITLE
Some issues with the self-hosting option

### ISSUE THREAD

**Issue by mlevin-dev** [winstxnhdw/nllb-api#172]
I experience the following issue when I try to run `main` tagged image locally.
```
docker run --rm \
  -e APP_PORT=7860 \
  -p 7860:7860 \
  -v ./cache:/home/user/.cache \
  ghcr.io/winstxnhdw/nllb-api:main
...
[2024-06-03 10:18:30 +0000] [37] [INFO] Waiting for application startup.
Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]
2024-06-03 10:18:37,897 INFO success: server entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2024-06-03 10:18:37,898 INFO success: caddy entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
```
It seems like server starts before whatever files the other process is trying to fetch become available. 

Then when I try to open Swagger server throws this error
```
{"level":"info","ts":1717410704.252975,"logger":"http.handlers.cache","msg":"Internal server error on endpoint /docs: [0xc0004b20a8]"}
{"level":"error","ts":1717410704.2530937,"logger":"http.log.error","msg":"context deadline exceeded","request": ...}
```

Several days ago I was able to start the container and open Swagger, but any request with more than ~100 tokens would result in a similar error `context deadline exceeded`.

It would be great if you could resolve these issues and push a stable, versioned image.
Many thanks in advance!

**Comment by winstxnhdw** [comment]
That’s really strange. Let me take a look.

**Comment by winstxnhdw** [comment]
Hey, I am not able to replicate your issue. Is your request taking longer than 10 seconds to process?

![image](https://github.com/winstxnhdw/nllb-api/assets/56998716/8f812925-01e7-4841-9e38-a1865053055b)

**Comment by winstxnhdw** [comment]
You can try extending the cache timeout variable.

```bash
docker run --rm \
  -e APP_PORT=7860 \
  -e CACHE_TIMEOUT=100
  -p 7860:7860 \
  -v ./cache:/home/user/.cache \
  ghcr.io/winstxnhdw/nllb-api:main
```

**Comment by mlevin-dev** [comment]
We tested a clean installation on several different machines (MacOS, Ubuntu), the issue is the same across all of them. The only potential limitation that applies is the abysmal internet connection speed (< 5Mb/s). It seems to me like something is timing out.

> Is your request taking longer than 10 seconds to process?
Probably yes, is there any way to disable all the timeouts?

**Comment by winstxnhdw** [comment]
You'll have to clone the repo and build the Docker image without the timeouts. Otherwise, you can just set it to an arbitrarily large value. The model only supports 1024 tokens anyways, so at some point, it shouldn't be taking THAT long to perform its predictions.

**Comment by winstxnhdw** [comment]
I have ended up removing the rate limiting module entirely in the latest commit.
