### ISSUE TITLE
I can translate from English to Japanese, but I can't translate from Japanese to English.

### ISSUE THREAD

**Issue by norick5243** [winstxnhdw/nllb-api#75]
I can translate from English to Japanese, but I can't translate from Japanese to English.
Is there any solution?

**Comment by winstxnhdw** [comment]
What issue are you facing? I am able to translate from Japanese to English.

![image](https://github.com/winstxnhdw/nllb-api/assets/56998716/682620ce-63f8-48fd-a5f6-c1d4b6aa4a3e)

**Comment by norick5243** [comment]
[こんにちは世界！ ] will be translated.
However, in cases such as [こんにちは] and [こんにちは世界], nothing is returned.
![1](https://github.com/winstxnhdw/nllb-api/assets/37971745/56e1854b-ab6e-4c1d-8b1a-96cab0a4478a)
![2](https://github.com/winstxnhdw/nllb-api/assets/37971745/19ba1b6c-9ef3-44bd-8f61-d49d59a7b633)
![3](https://github.com/winstxnhdw/nllb-api/assets/37971745/dd770181-e1dc-4fe0-881c-94c381340431)

**Comment by norick5243** [comment]
It was a beginner's mistake. I was able to translate it successfully. thank you very much.
