### ISSUE TITLE
Some text is missed

### ISSUE THREAD

**Issue by niksedk** [winstxnhdw/nllb-api#79]
Hi there,

When running this json through swagger:

````json
{
  "text": "Hi George. Roy, got to talk to you.",
  "source": "eng_Latn",
  "target": "dan_Latn"
}
````

I get this result: `Roy, jeg skal tale med dig.`
The `Hi George` part is missing.

Screenshot:
![image](https://github.com/winstxnhdw/nllb-api/assets/1261331/92327ccc-4b4d-42af-8f9f-f43b3a5b68d4)

![image](https://github.com/winstxnhdw/nllb-api/assets/1261331/f25a2281-c6d9-4766-adc5-aea96b308149)

Any ideas?

**Comment by winstxnhdw** [comment]
That's really really strange. It seems that whenever `Roy, got to talk to you.` is used as the second sentence, this issue occurs. I could replicate it with Spanish too. 

I'll have to look more into this but my guess is that the model is the issue here. I'll get back to you again soon.

**Comment by winstxnhdw** [comment]
Unfortunately, the issue is indeed with the model itself. There is nothing we can do about this.

**Comment by niksedk** [comment]
Thanks for the info.
